New sign up: Login Functionality
gt-grouporder/backend pull request #1
Opened 2024-10-06 17:02 UTC by Carbinski

Added login functionality.

Compared user info and password info to data base. If not found or not matching then responds with error signing in. Otherwise responds with secret token

2024-10-06 17:04 UTC, Carbinski commented
Also I made some changes so it works on my local mongo db rather than the one you set up

2024-10-06 23:12 UTC, reiden-webber requested changes

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +    const object = await userCollection.find({
```suggestion
    const object = await userCollection.find(user)
```

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +  let userID;
remove unused line

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +    console.log(object);
remove debug statement

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +      res.status(202).send({token: TOKEN_SECRET});
Send the generated token instead of TOKEN_SECRET

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +    if (object.length > 0) {
Add a comment here what does object length look like and why if it is greater than zero then it exists

2024-10-06 23:12 UTC, reiden-webber commented on index.js
> +      res.status(501).send('Error logging in');
500s messages are reserved for server-side errors and 400s messages are for user errors I think. (fact check me?). I'm guessing that this line after the else statement means the user logged in a username or password that doesn't exist

2024-10-08 02:07 UTC, Carbinski commented on index.js
> +      res.status(501).send('Error logging in');
oh lol I was just making up error codes

2024-10-08 02:16 UTC, Carbinski commented
I think I made the changes using the in app editor.

2024-11-20 04:47 UTC, closed without merging